# Banknotes by SainttX
note:
  material: PAPER
  data: 0
  name: "&lBanknote"
  lore:
  - "$[money]"
  - "Withdrawn by [player]"

messages:
  invalid-note: "This banknote is invalid! It has been removed from your inventory"
  nothing-in-hand: "There is nothing in your hand for you to redeem"
  note-redeemed: "Banknote for $[money] has been redeemed"
