# Banknotes by SainttX
# WARNING: If your users have notes and you modify this,
#          their notes will be invalid and not registered by the plugin anymore
note:
  material: PAPER
  data: 0
  name: "&lBanknote"
  lore:
  - "$[money]"
  - "Withdrawn by [player]"

messages:
  insufficient-funds: "You do not have enough money to withdraw this amount"
  insufficient-permissions: "You do not have enough permissions"
  inventory-full: "Please have a space open in your inventory to create a banknote"
  invalid-note: "This banknote is invalid! It has been removed from your inventory"
  invalid-number: "You provided an invalid number"
  note-created: "You created a note for $[money]"
  note-redeemed: "Banknote for $[money] has been redeemed"
  nothing-in-hand: "There is nothing in your hand for you to redeem"
  less-than-minimum: "The amount you entered is less than the minimum allowed amount of"
  
settings:
  minimum-withdraw-amount: 10.0
