name: Banknotes
version: 0.1.0
description: A plugin to withdraw money and store it as a paper note
author: SainttX

main: me.sainttx.banknotes.BanknotePlugin
depend: [Vault]

commands:
  withdraw:
    description: Withdraw money as a note
  deposit:
    description: Deposit a note

permissions:
  auction.*:
    description: Gives access to all Auction commands
    children:
      auction.bid: true
      auction.start: true
      auction.end: true
      auction.end.bypass: true
      auction.info: true
      auction.ignore: true
      auction.tax.exempt: true
      auction.disable.bypass: true
      auction.disable: true
      auction.enable: true
      auction.reload: true
      auction.bypass.startdelay: true
  auction.bid:
    description: Allows you to bid on auctions
    default: true
  auction.start:
    description: Allows you to start auctions
    default: true
  auction.creative:
    description: Allows you to start auctions in CREATIVE mode
    default: op
  auction.end:
    description: Allows you to end auctions
    default: op
  auction.end.bypass:
    description: Allows you to end auctions when ending is disallowed
    default: op
  auction.info:
    description: Allows you to view auction information
    default: true
  auction.ignore:
    description: Allows you to ignore auction messages
    default: true
  auction.tax.exempt:
    description: Enables you to avoid auction taxes
    default: op
  auction.bypass.disable:
    description: Enables you to start auctions in disabled mode
    default: op
  auction.bypass.startdelay:
    description: Allows you to bypass the delay between auctions
    default: op
  auction.disable:
    description: Allows you to put Auctions in permission-only mode
    default: op
  auction.enable:
    description: Allows you to enable auctioning
    default: op
  auction.reload:
    description: Allows you to reload the auction configuration
    default: op